#!/usr/bin/env python3
"""
Load Tamil words from Tamil Wikipedia dump into the database.
Downloads tawiki dump, extracts Tamil words, and loads them via SQL.

Usage:
  python scripts/load_tamil_wiki_words.py --max-words 200000

For local file:
  python scripts/load_tamil_wiki_words.py --local-file /path/to/tawiki.xml.bz2 --max-words 200000
"""

import argparse
import bz2
import gzip
import os
import re
import sys
import tempfile
import urllib.request
import subprocess
from collections import Counter
from pathlib import Path

TAMIL_WORD_RE = re.compile(r"[\u0B80-\u0BFF]+")

# Tamil to Roman transliteration
INDEP_VOWELS = {
    "அ": "a", "ஆ": "aa", "இ": "i", "ஈ": "ii", "உ": "u", "ஊ": "uu",
    "எ": "e", "ஏ": "ee", "ஐ": "ai", "ஒ": "o", "ஓ": "oo", "ஔ": "au", "ஃ": "h",
}

VOWEL_SIGNS = {
    "ா": "a", "ி": "i", "ீ": "i", "ு": "u", "ூ": "u",
    "ெ": "e", "ே": "e", "ை": "ai", "ொ": "o", "ோ": "o", "ௌ": "au",
}

PULLI = "்"

CONSONANTS = {
    "க": "k", "ங": "ng", "ச": "ch", "ஜ": "j", "ஞ": "nj",
    "ட": "t", "ண": "n", "த": "th", "ந": "n", "ப": "p",
    "ம": "m", "ய": "y", "ர": "r", "ல": "l", "வ": "v",
    "ழ": "zh", "ள": "l", "ற": "r", "ன": "n",
    "ஷ": "sh", "ஸ": "s", "ஹ": "h", "ஶ": "sh",
}

# Common Tamil words with their romanizations (for validation)
COMMON_WORDS = {
    "வடை": "vadai",
    "இட்லி": "idli",
    "தோசை": "dosai",
    "சாம்பார்": "sambar",
    "ரசம்": "rasam",
    "பொங்கல்": "pongal",
    "வணக்கம்": "vanakkam",
    "நன்றி": "nandri",
    "தமிழ்": "tamil",
}


def romanize_tamil(word: str) -> str:
    """Convert Tamil word to romanized form."""
    if not word:
        return ""
    out = []
    i = 0
    while i < len(word):
        ch = word[i]
        if ch in INDEP_VOWELS:
            out.append(INDEP_VOWELS[ch])
        elif ch in CONSONANTS:
            base = CONSONANTS[ch]
            next_ch = word[i + 1] if i + 1 < len(word) else ""
            if next_ch in VOWEL_SIGNS:
                out.append(base + VOWEL_SIGNS[next_ch])
                i += 1
            elif next_ch == PULLI:
                out.append(base)
                i += 1
            else:
                out.append(base + "a")
        i += 1
    return "".join(out).lower()


def open_maybe_compressed(path: str):
    """Open file, handling .bz2 and .gz compression."""
    if path.endswith(".bz2"):
        return bz2.open(path, "rt", encoding="utf-8", errors="ignore")
    if path.endswith(".gz"):
        return gzip.open(path, "rt", encoding="utf-8", errors="ignore")
    return open(path, "rt", encoding="utf-8", errors="ignore")


def download_tawiki(dest_dir: str) -> str:
    """Download latest Tamil Wikipedia dump."""
    url = "https://dumps.wikimedia.org/tawiki/latest/tawiki-latest-pages-articles.xml.bz2"
    filename = os.path.basename(url)
    dest = os.path.join(dest_dir, filename)
    
    if os.path.exists(dest):
        print(f"[CORPUS] Using existing file: {dest}")
        return dest
    
    print(f"[CORPUS] Downloading Tamil Wikipedia dump...")
    print(f"[CORPUS] URL: {url}")
    print(f"[CORPUS] This may take a while (file is ~500MB)")
    urllib.request.urlretrieve(url, dest)
    print(f"[CORPUS] Downloaded: {dest}")
    return dest


def collect_words(stream, max_words: int, min_len: int = 2, max_len: int = 20) -> Counter:
    """Extract Tamil words from stream."""
    counts = Counter()
    line_count = 0
    
    for line in stream:
        line_count += 1
        if line_count % 100000 == 0:
            print(f"[CORPUS] Processed {line_count:,} lines, found {len(counts):,} unique words...")
        
        for token in TAMIL_WORD_RE.findall(line):
            w = token.strip()
            if not w or len(w) < min_len or len(w) > max_len:
                continue
            counts[w] += 1
            
            if len(counts) >= max_words:
                print(f"[CORPUS] Reached max words limit ({max_words:,})")
                return counts
    
    return counts


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def write_sql(path: str, entries: list, source: str):
    """Write SQL file for inserting words."""
    with open(path, "w", encoding="utf-8") as f:
        f.write("-- Tamil Wikipedia corpus import\n")
        f.write("-- Generated by load_tamil_wiki_words.py\n\n")
        f.write("BEGIN;\n\n")
        
        batch = []
        for tamil, roman, freq in entries:
            if not tamil or not roman:
                continue
            batch.append(
                f"('{sql_escape(tamil)}','{sql_escape(roman)}','[]',{freq},'common','{sql_escape(source)}',false)"
            )
            if len(batch) >= 500:
                f.write(
                    "INSERT INTO tamil_words (tamil_text, transliteration, alternate_spellings, frequency, category, source, is_verified) VALUES\n"
                )
                f.write(",\n".join(batch))
                f.write(
                    "\nON CONFLICT (transliteration) DO UPDATE SET frequency = GREATEST(tamil_words.frequency, EXCLUDED.frequency);\n\n"
                )
                batch = []
        
        if batch:
            f.write(
                "INSERT INTO tamil_words (tamil_text, transliteration, alternate_spellings, frequency, category, source, is_verified) VALUES\n"
            )
            f.write(",\n".join(batch))
            f.write(
                "\nON CONFLICT (transliteration) DO UPDATE SET frequency = GREATEST(tamil_words.frequency, EXCLUDED.frequency);\n\n"
            )
        
        f.write("COMMIT;\n")


def add_common_words(entries: list) -> list:
    """Add common words that might be missing."""
    existing_tamil = {e[0] for e in entries}
    existing_roman = {e[1] for e in entries}
    
    added = 0
    for tamil, roman in COMMON_WORDS.items():
        if tamil not in existing_tamil and roman not in existing_roman:
            entries.append((tamil, roman, 1000))  # High frequency for common words
            added += 1
    
    if added:
        print(f"[CORPUS] Added {added} common words")
    
    return entries


def main():
    parser = argparse.ArgumentParser(description="Load Tamil words from Wikipedia")
    parser.add_argument("--local-file", help="Path to local Wikipedia dump file")
    parser.add_argument("--max-words", type=int, default=200000, help="Maximum words to extract")
    parser.add_argument("--output", default="data/tamil_wiki_corpus.sql", help="Output SQL file")
    parser.add_argument("--load-db", action="store_true", help="Load directly into database")
    parser.add_argument("--database-url", help="Database URL (or uses DATABASE_URL env)")
    args = parser.parse_args()
    
    # Get source file
    if args.local_file:
        if not os.path.exists(args.local_file):
            print(f"[ERROR] File not found: {args.local_file}")
            sys.exit(1)
        source_path = args.local_file
        print(f"[CORPUS] Using local file: {source_path}")
    else:
        tmp_dir = tempfile.mkdtemp(prefix="tawiki_")
        source_path = download_tawiki(tmp_dir)
    
    # Extract words
    print(f"[CORPUS] Extracting Tamil words (max {args.max_words:,})...")
    with open_maybe_compressed(source_path) as f:
        counts = collect_words(f, args.max_words)
    
    print(f"[CORPUS] Found {len(counts):,} unique Tamil words")
    
    # Build romanization map
    roman_map = {}
    for tamil, freq in counts.most_common(args.max_words):
        roman = romanize_tamil(tamil)
        if not roman or len(roman) < 2:
            continue
        prev = roman_map.get(roman)
        if prev is None or freq > prev[1]:
            roman_map[roman] = (tamil, freq)
    
    entries = [(t, r, freq) for r, (t, freq) in roman_map.items()]
    entries.sort(key=lambda x: x[2], reverse=True)
    
    # Add common words
    entries = add_common_words(entries)
    
    if not entries:
        print("[ERROR] No entries produced. Exiting.")
        sys.exit(1)
    
    print(f"[CORPUS] Total entries: {len(entries):,}")
    
    # Write SQL file
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    write_sql(args.output, entries, "tawiki_corpus")
    print(f"[CORPUS] SQL written: {args.output}")
    
    # Load into database if requested
    if args.load_db:
        db_url = args.database_url or os.environ.get("DATABASE_URL")
        if not db_url:
            print("[ERROR] No database URL provided. Use --database-url or set DATABASE_URL env")
            sys.exit(1)
        
        print(f"[CORPUS] Loading into database...")
        result = subprocess.run(
            ["psql", db_url, "-f", args.output],
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            print("[CORPUS] ✅ Successfully loaded into database!")
        else:
            print(f"[ERROR] Failed to load: {result.stderr}")
            sys.exit(1)
    else:
        print(f"\n[INFO] To load into database, run:")
        print(f"  psql $DATABASE_URL -f {args.output}")
        print(f"  OR")
        print(f"  python {sys.argv[0]} --load-db --database-url YOUR_DB_URL")


if __name__ == "__main__":
    main()
